// Auto-generated by scripts/generate-media.mjs — do not edit by hand.
// Re-run: npm run generate-media

export const mediaRoot = '/images';

export const imageFiles = [
  "0644e2d3359d981feb82a21fb3e3ef48.jpg",
  "0d3afd56-1969-48fb-a16b-f29dc35080c8.jpg",
  "19a60461-69f4-4002-a9db-be5a12ad17d7.jpg",
  "1b236216-6e40-42ad-b012-26c8c28cbe13.JPG",
  "1bf7e1b3-6883-4820-bc68-63d6ccb1a6d8.JPG",
  "2020-09-08-102552436.jpg",
  "20210911_152631.jpg",
  "20210912_180333.jpg",
  "20210926_120542.jpg",
  "20211008_132039.jpg",
  "20211008_133321.jpg",
  "20211008_133856.jpg",
  "20211013_162827.jpg",
  "20211013_162846.jpg",
  "20211013_163636.jpg",
  "20211030_174305.jpg",
  "20220408_155740.jpg",
  "20220409_154837.jpg",
  "239d6136-9ffb-4625-8968-4452faef8b84.JPG",
  "2698c45a-2081-460f-801e-314f71523437.jpg",
  "345bd630-744c-43f4-a25c-026781ec7c43.jpg",
  "4549aa2f-39ff-4f61-bb30-818839245e0e.JPG",
  "473354ab-d958-4439-a5eb-f841e1104b30.JPG",
  "62d597a9-b5ce-4b4b-a8a3-c7697537beda.jpg",
  "65506f23-a830-4bb4-ac98-ca0120b4af50.jpg",
  "98a76dcd-af7a-475e-84a6-2e0ed053c184.jpg",
  "AirBrush_20210915091935.jpg",
  "b0b6bb3bc940388b1c43fb911a8c8c48.jpg",
  "b610ad36-f8f8-4023-95ec-20aa582891c2.JPG",
  "c2823eb6-1cb8-4104-8685-26e2000c2dfd.JPG",
  "c6f7e36f-943e-472a-9923-0b8a4e3df597.JPG",
  "df91f523-3b9e-4469-b13a-6bb71727baa4.JPG",
  "e82a123e-b2eb-43cf-bdfd-bb33de2e3fc2.JPG",
  "f5b5cbb1-4163-4b28-b197-e57b1a3cab45.JPG",
  "FaceApp_1666558149537.jpg",
  "FaceApp_1667144746219.jpg",
  "FaceApp_1678383632872.jpg",
  "FaceApp_1679300957031.jpg",
  "IMG_20200122_124119.jpg",
  "IMG_20200325_105419.jpg",
  "IMG_20200325_110531.jpg",
  "IMG_20200920_202909.jpg",
  "IMG_20210224_140608.jpg",
  "IMG_20210224_223434_173.jpg",
  "IMG_20220714_110633_596.webp",
  "IMG_20220905_160301_958.webp",
  "IMG_4928_Original.JPG",
  "IMG_8503.jpg",
  "IMG-20190127-WA0014.jpg",
  "IMG-20190127-WA0018.jpg",
  "IMG-20190713-WA0059.jpg",
  "IMG-20190713-WA0060.jpg",
  "IMG-20190717-WA0071.jpg",
  "IMG-20190717-WA0072.jpg",
  "IMG-20190717-WA0073.jpg",
  "IMG-20190922-WA0000.jpg",
  "IMG-20191102-WA0034.jpg",
  "IMG-20191102-WA0063.jpg",
  "IMG-20200120-WA0041.jpg",
  "IMG-20210604-WA0160.jpg",
  "IMG-20210604-WA0210.jpg",
  "IMG-20210618-WA0085.jpg",
  "IMG-20210724-WA0120.jpg",
  "IMG-20210913-WA0086.jpg",
  "IMG-20210913-WA0106.jpg",
  "IMG-20220407-WA0144.jpg",
  "IMG-20220408-WA0089.jpg",
  "IMG-20220916-WA0057.jpg",
  "IMG-20221203-WA0070.jpg",
  "IMG-20221225-WA0063.jpg",
  "IMG-20230502-WA0038.jpg",
  "IMG-20230618-WA0013.jpg",
  "IMG-20230806-WA0202.jpg",
  "IMG-20240602-WA0218.jpg",
  "IMG-20240602-WA0228.jpg",
  "IMG-26677710.jpg",
  "Screenshot_20200531_163209.jpg",
  "Screenshot_20200818_204054.jpg",
  "Screenshot_20201209_190202.jpg",
  "Screenshot_20210807-144652_Gallery.jpg",
  "Screenshot_20210929-125030_Gallery.jpg",
  "Screenshot_20211226-192213_Photos.jpg",
  "Screenshot_20211226-192430_Photos.jpg",
  "Screenshot_20211226-220210_Gallery.jpg",
  "Screenshot_20211227-115006_Gallery.jpg",
  "Screenshot_20220610-071021_Gallery.jpg",
  "Screenshot_20220610-071036_Gallery.jpg",
  "Screenshot_20220816-074245_Gallery.jpg",
  "Screenshot_20230303-225824_WhatsApp.jpg",
  "Screenshot_20230630-072945_Gallery.jpg",
  "Screenshot_20240602_161710_Gallery_Original.JPG",
  "Screenshot_20250223_192606.jpg",
  "Snapchat-1255359043.jpg",
  "Snapchat-1895527567.jpg",
  "VideoCapture_20220831-115150.jpg"
] as const;

export const videoFiles = [
  "0b321244-920d-4a6a-beaa-d720fca0fd1e.MP4",
  "620ed5e2-954c-4120-a058-e0b7ee890a93.MP4",
  "92cba4ee-9377-4722-bb16-00379941b2eb.mov",
  "93e3be12-32f8-4565-9a60-d9ed43be272c.MP4",
  "c4b80788-bf18-47fc-b28d-c26f4bc7d561.MP4",
  "cf67c512-7ef1-43c1-9c62-0427e8313050.MP4",
  "eaa4afb0-4b2a-434b-a863-ce93ad29aad7.MP4",
  "f819e8a7-f43c-4538-a982-7ff035fe8cca.mov"
] as const;

export const skippedFiles = [
  "IMG_8160.HEIC",
  "IMG_8807.HEIC",
  "IMG_8809.HEIC"
] as const;

export const mediaImages = imageFiles.map((file) => `${mediaRoot}/${file}`);

export const mediaVideos = videoFiles.map((file) => `${mediaRoot}/${file}`);

export const volumeSlugs = [
  "atelier-noir",
  "silent-frames",
  "afterlight-studio",
  "city-echoes"
] as const;

export type VolumeSlug = (typeof volumeSlugs)[number];

const volumeImageChunks: string[][] = [
  [
    "/images/0644e2d3359d981feb82a21fb3e3ef48.jpg",
    "/images/0d3afd56-1969-48fb-a16b-f29dc35080c8.jpg",
    "/images/19a60461-69f4-4002-a9db-be5a12ad17d7.jpg",
    "/images/1b236216-6e40-42ad-b012-26c8c28cbe13.JPG",
    "/images/1bf7e1b3-6883-4820-bc68-63d6ccb1a6d8.JPG",
    "/images/2020-09-08-102552436.jpg",
    "/images/20210911_152631.jpg",
    "/images/20210912_180333.jpg",
    "/images/20210926_120542.jpg",
    "/images/20211008_132039.jpg",
    "/images/20211008_133321.jpg",
    "/images/20211008_133856.jpg",
    "/images/20211013_162827.jpg",
    "/images/20211013_162846.jpg",
    "/images/20211013_163636.jpg",
    "/images/20211030_174305.jpg",
    "/images/20220408_155740.jpg",
    "/images/20220409_154837.jpg",
    "/images/239d6136-9ffb-4625-8968-4452faef8b84.JPG",
    "/images/2698c45a-2081-460f-801e-314f71523437.jpg",
    "/images/345bd630-744c-43f4-a25c-026781ec7c43.jpg",
    "/images/4549aa2f-39ff-4f61-bb30-818839245e0e.JPG",
    "/images/473354ab-d958-4439-a5eb-f841e1104b30.JPG",
    "/images/62d597a9-b5ce-4b4b-a8a3-c7697537beda.jpg"
  ],
  [
    "/images/65506f23-a830-4bb4-ac98-ca0120b4af50.jpg",
    "/images/98a76dcd-af7a-475e-84a6-2e0ed053c184.jpg",
    "/images/AirBrush_20210915091935.jpg",
    "/images/b0b6bb3bc940388b1c43fb911a8c8c48.jpg",
    "/images/b610ad36-f8f8-4023-95ec-20aa582891c2.JPG",
    "/images/c2823eb6-1cb8-4104-8685-26e2000c2dfd.JPG",
    "/images/c6f7e36f-943e-472a-9923-0b8a4e3df597.JPG",
    "/images/df91f523-3b9e-4469-b13a-6bb71727baa4.JPG",
    "/images/e82a123e-b2eb-43cf-bdfd-bb33de2e3fc2.JPG",
    "/images/f5b5cbb1-4163-4b28-b197-e57b1a3cab45.JPG",
    "/images/FaceApp_1666558149537.jpg",
    "/images/FaceApp_1667144746219.jpg",
    "/images/FaceApp_1678383632872.jpg",
    "/images/FaceApp_1679300957031.jpg",
    "/images/IMG_20200122_124119.jpg",
    "/images/IMG_20200325_105419.jpg",
    "/images/IMG_20200325_110531.jpg",
    "/images/IMG_20200920_202909.jpg",
    "/images/IMG_20210224_140608.jpg",
    "/images/IMG_20210224_223434_173.jpg",
    "/images/IMG_20220714_110633_596.webp",
    "/images/IMG_20220905_160301_958.webp",
    "/images/IMG_4928_Original.JPG",
    "/images/IMG_8503.jpg"
  ],
  [
    "/images/IMG-20190127-WA0014.jpg",
    "/images/IMG-20190127-WA0018.jpg",
    "/images/IMG-20190713-WA0059.jpg",
    "/images/IMG-20190713-WA0060.jpg",
    "/images/IMG-20190717-WA0071.jpg",
    "/images/IMG-20190717-WA0072.jpg",
    "/images/IMG-20190717-WA0073.jpg",
    "/images/IMG-20190922-WA0000.jpg",
    "/images/IMG-20191102-WA0034.jpg",
    "/images/IMG-20191102-WA0063.jpg",
    "/images/IMG-20200120-WA0041.jpg",
    "/images/IMG-20210604-WA0160.jpg",
    "/images/IMG-20210604-WA0210.jpg",
    "/images/IMG-20210618-WA0085.jpg",
    "/images/IMG-20210724-WA0120.jpg",
    "/images/IMG-20210913-WA0086.jpg",
    "/images/IMG-20210913-WA0106.jpg",
    "/images/IMG-20220407-WA0144.jpg",
    "/images/IMG-20220408-WA0089.jpg",
    "/images/IMG-20220916-WA0057.jpg",
    "/images/IMG-20221203-WA0070.jpg",
    "/images/IMG-20221225-WA0063.jpg",
    "/images/IMG-20230502-WA0038.jpg",
    "/images/IMG-20230618-WA0013.jpg"
  ],
  [
    "/images/IMG-20230806-WA0202.jpg",
    "/images/IMG-20240602-WA0218.jpg",
    "/images/IMG-20240602-WA0228.jpg",
    "/images/IMG-26677710.jpg",
    "/images/Screenshot_20200531_163209.jpg",
    "/images/Screenshot_20200818_204054.jpg",
    "/images/Screenshot_20201209_190202.jpg",
    "/images/Screenshot_20210807-144652_Gallery.jpg",
    "/images/Screenshot_20210929-125030_Gallery.jpg",
    "/images/Screenshot_20211226-192213_Photos.jpg",
    "/images/Screenshot_20211226-192430_Photos.jpg",
    "/images/Screenshot_20211226-220210_Gallery.jpg",
    "/images/Screenshot_20211227-115006_Gallery.jpg",
    "/images/Screenshot_20220610-071021_Gallery.jpg",
    "/images/Screenshot_20220610-071036_Gallery.jpg",
    "/images/Screenshot_20220816-074245_Gallery.jpg",
    "/images/Screenshot_20230303-225824_WhatsApp.jpg",
    "/images/Screenshot_20230630-072945_Gallery.jpg",
    "/images/Screenshot_20240602_161710_Gallery_Original.JPG",
    "/images/Screenshot_20250223_192606.jpg",
    "/images/Snapchat-1255359043.jpg",
    "/images/Snapchat-1895527567.jpg",
    "/images/VideoCapture_20220831-115150.jpg"
  ]
];

const volumeVideoChunks: string[][] = [
  [
    "/images/0b321244-920d-4a6a-beaa-d720fca0fd1e.MP4",
    "/images/620ed5e2-954c-4120-a058-e0b7ee890a93.MP4"
  ],
  [
    "/images/92cba4ee-9377-4722-bb16-00379941b2eb.mov",
    "/images/93e3be12-32f8-4565-9a60-d9ed43be272c.MP4"
  ],
  [
    "/images/c4b80788-bf18-47fc-b28d-c26f4bc7d561.MP4",
    "/images/cf67c512-7ef1-43c1-9c62-0427e8313050.MP4"
  ],
  [
    "/images/eaa4afb0-4b2a-434b-a863-ce93ad29aad7.MP4",
    "/images/f819e8a7-f43c-4538-a982-7ff035fe8cca.mov"
  ]
];

export function getVolumeImages(slug: VolumeSlug): string[] {
  const index = volumeSlugs.indexOf(slug);
  return volumeImageChunks[index] ?? [];
}

export function getVolumeVideos(slug: VolumeSlug): string[] {
  const index = volumeSlugs.indexOf(slug);
  return volumeVideoChunks[index] ?? [];
}

export const home = {
  "cover": "/images/Screenshot_20220610-071021_Gallery.jpg",
  "openingLeft": "/images/IMG_20200325_105419.jpg",
  "openingRight": "/images/IMG_20210224_140608.jpg",
  "spread01": "/images/IMG-20230806-WA0202.jpg",
  "spread02a": "/images/2020-09-08-102552436.jpg",
  "spread02b": "/images/20210911_152631.jpg",
  "spread02c": "/images/20210912_180333.jpg",
  "spread03Left": "/images/20210926_120542.jpg",
  "spread03Right": "/images/20211008_132039.jpg",
  "videos": [
    "/images/0b321244-920d-4a6a-beaa-d720fca0fd1e.MP4",
    "/images/620ed5e2-954c-4120-a058-e0b7ee890a93.MP4"
  ]
};

export const about = {
  "foreword": "/images/IMG_20200325_110531.jpg"
};
