import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');
const mediaDir = path.join(root, 'public/images');

const imageExts = ['.jpg', '.jpeg', '.png', '.webp', '.gif'];
const videoExts = ['.mp4', '.mov', '.webm'];

const files = fs
  .readdirSync(mediaDir)
  .filter((file) => file !== '.gitkeep')
  .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' }));

const isImage = (file) =>
  imageExts.some((ext) => file.toLowerCase().endsWith(ext));
const isVideo = (file) =>
  videoExts.some((ext) => file.toLowerCase().endsWith(ext));

const imageFiles = files.filter(isImage);
const videoFiles = files.filter(isVideo);
const skippedFiles = files.filter((file) => !isImage(file) && !isVideo(file));

const volumeSlugs = [
  'atelier-noir',
  'silent-frames',
  'afterlight-studio',
  'city-echoes',
];

function toSrc(file) {
  return `/images/${file}`;
}

function chunk(items, count) {
  const size = Math.ceil(items.length / count);
  return Array.from({ length: count }, (_, index) =>
    items.slice(index * size, index * size + size)
  );
}

const volumeImageChunks = chunk(imageFiles, volumeSlugs.length);
const volumeVideoChunks = chunk(videoFiles, volumeSlugs.length);

// Featured slots use gallery numbers (Memory 001, 041, 073, etc.)
const featuredGallery = {
  aboutForeword: 41,
  herSmile: 73,
  cover: 86,
  openingLeft: 40,
  openingRight: 43,
};

function galleryByNumber(n) {
  const file = imageFiles[n - 1];
  return file ? toSrc(file) : toSrc(imageFiles[0]);
}

const mediaImagePaths = imageFiles.map(toSrc);
const mediaVideoPaths = videoFiles.map(toSrc);

const homeFeatured = {
  cover: galleryByNumber(featuredGallery.cover),
  openingLeft: galleryByNumber(featuredGallery.openingLeft),
  openingRight: galleryByNumber(featuredGallery.openingRight),
  spread01: galleryByNumber(featuredGallery.herSmile),
  spread02a: mediaImagePaths[5] ?? mediaImagePaths[0] ?? '',
  spread02b: mediaImagePaths[6] ?? mediaImagePaths[0] ?? '',
  spread02c: mediaImagePaths[7] ?? mediaImagePaths[0] ?? '',
  spread03Left: mediaImagePaths[8] ?? mediaImagePaths[0] ?? '',
  spread03Right: mediaImagePaths[9] ?? mediaImagePaths[0] ?? '',
  videos: mediaVideoPaths.slice(0, 2),
};

const aboutFeatured = {
  foreword: galleryByNumber(featuredGallery.aboutForeword),
};

const output = `// Auto-generated by scripts/generate-media.mjs — do not edit by hand.
// Re-run: npm run generate-media

export const mediaRoot = '/images';

export const imageFiles = ${JSON.stringify(imageFiles, null, 2)} as const;

export const videoFiles = ${JSON.stringify(videoFiles, null, 2)} as const;

export const skippedFiles = ${JSON.stringify(skippedFiles, null, 2)} as const;

export const mediaImages = imageFiles.map((file) => \`\${mediaRoot}/\${file}\`);

export const mediaVideos = videoFiles.map((file) => \`\${mediaRoot}/\${file}\`);

export const volumeSlugs = ${JSON.stringify(volumeSlugs, null, 2)} as const;

export type VolumeSlug = (typeof volumeSlugs)[number];

const volumeImageChunks: string[][] = ${JSON.stringify(
  volumeImageChunks.map((group) => group.map(toSrc)),
  null,
  2
)};

const volumeVideoChunks: string[][] = ${JSON.stringify(
  volumeVideoChunks.map((group) => group.map(toSrc)),
  null,
  2
)};

export function getVolumeImages(slug: VolumeSlug): string[] {
  const index = volumeSlugs.indexOf(slug);
  return volumeImageChunks[index] ?? [];
}

export function getVolumeVideos(slug: VolumeSlug): string[] {
  const index = volumeSlugs.indexOf(slug);
  return volumeVideoChunks[index] ?? [];
}

export const home = ${JSON.stringify(homeFeatured, null, 2)};

export const about = ${JSON.stringify(aboutFeatured, null, 2)};
`;

fs.writeFileSync(path.join(root, 'content/media.ts'), output);

console.log(
  `Generated content/media.ts — ${imageFiles.length} images, ${videoFiles.length} videos, ${skippedFiles.length} skipped`
);

if (skippedFiles.length > 0) {
  console.log('Skipped (convert to JPG to use):', skippedFiles.join(', '));
}
